services:

  spaced-repetition-bot-db:
    container_name: spaced-repetition-bot-db
    image: postgres:17.5-alpine
    ports:
      - '5429:5432'
    environment:
      POSTGRES_USER: ${TELEGRAM_BOT_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${TELEGRAM_BOT_DB_PASSWORD:-postgres}
      POSTGRES_DB: spaced-repetition-bot-db
      shared_buffers: 32MB  # По умолчанию 128MB
      maintenance_work_mem: 32MB  # По умолчанию 64MB
      max_connections: 10  # По умолчанию 100
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 10m

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_HEAP_SIZE: "128m"  # По умолчанию 1G
      ZOO_MAX_CLIENT_CNXNS: 30  # По умолчанию 60
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 10m

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_INTERNAL://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx384m -Xms128m"  # По умолчанию 1G
      KAFKA_NUM_PARTITIONS: "1"
      KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
      KAFKA_LOG_RETENTION_BYTES: "52428800"  # 50MB максимум на топик
      KAFKA_LOG_SEGMENT_BYTES: "10485760"  # 10MB (меньше чем стандартные 1GB)
      KAFKA_LOG_CLEANER_DEDUPE_BUFFER_SIZE: "67108864" # 64MB вместо 128MB
      KAFKA_NUM_IO_THREADS: "4"  # По умолчанию 8
      KAFKA_NUM_NETWORK_THREADS: "2"  # По умолчанию 3
      KAFKA_QUEUED_MAX_REQUESTS: "100"  # По умолчанию 500 (можно уменьшить)
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 10m

#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui
#    ports:
#      - "8082:8080"
#    depends_on:
#      - kafka
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
#    restart: on-failure

  spaced-repetition-bot:
    image: ouidockeruser/spaced-repetition-bot:latest
    container_name: spaced-repetition-bot
    restart: unless-stopped
    environment:
      _JAVA_OPTIONS: -Xmx64m -Xms32m
      TELEGRAM_BOT_DB_HOST: spaced-repetition-bot-db
      TELEGRAM_BOT_DB_PORT: 5432
      TELEGRAM_BOT_DB_USER: ${TELEGRAM_BOT_DB_USER:-postgres}
      TELEGRAM_BOT_DB_PASSWORD: ${TELEGRAM_BOT_DB_PASSWORD:-postgres}
      TELEGRAM_BOT_PORT: ${TELEGRAM_BOT_PORT:-8080}
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME:-SpacedRepetitionBot}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_CREATOR_ID: ${TELEGRAM_BOT_CREATOR_ID}
      GIT_SSH_PASSPHRASE: ${GIT_SSH_PASSPHRASE}
      GIT_WEBHOOK_SECRET: ${GIT_WEBHOOK_SECRET}
      GIT_TOKEN: ${GIT_TOKEN}
      ENCRYPTION_PASSWORD: ${ENCRYPTION_PASSWORD}
      ENCRYPTION_SALT: ${ENCRYPTION_SALT}
    ports:
      - "9100:8080"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    depends_on:
      - spaced-repetition-bot-db
      - kafka