name: Generate and commit badges

on:
  push:
    branches:
      - main

jobs:
  code-coverage-badges:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B verify

      - name: Generate Coverage Badges for Spaced Repetition Bot
        id: jacocoSpacedRepetitionBot
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: spaced-repetition-bot/target/jacoco-report/jacoco.csv
          coverage-badge-filename: .github/badges/jacoco_spaced_repetition_bot.svg
          coverage-label: coverage (Spaced Repetition Bot)

      - name: Generate Coverage Badges for Spaced Repetition Web
        id: jacocoSpacedRepetitionWeb
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: spaced-repetition-web/target/jacoco-report/jacoco.csv
          coverage-badge-filename: .github/badges/jacoco_spaced_repetition_web.svg
          coverage-label: coverage (Spaced Repetition Web)

      - name: Commit the badge (if it changed)
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git checkout -b badges-branch 2>/dev/null || git checkout badges-branch
          git add .github/badges
          git commit -m "Update coverage badges"
          git push origin badges-branch --force
