name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      spaced-repetition-bot: ${{ steps.filter.outputs.spaced-repetition-bot }}
      spaced-repetition-web: ${{ steps.filter.outputs.spaced-repetition-web }}
      docker-compose: ${{ steps.filter.outputs.docker-compose }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            spaced-repetition-bot: ['spaced-repetition-bot/**']
            spaced-repetition-web: ['spaced-repetition-web/**']
            docker-compose: ['docker-compose.yml']

  push-docker-compose-to-remote-server:
    name: Push docker-compose.yaml to remote server
    runs-on: ubuntu-latest
    needs: [detect-changes]
    steps:
      - uses: actions/checkout@v4
      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: "github-spaced-repetition"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/github-spaced-repetition"

  build-and-push-images-to-dockerhub:
    name: Build and Push Images to DockerHub
    runs-on: ubuntu-latest
    needs: [detect-changes]
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Bot Image
        if: ${{ needs.detect-changes.outputs.spaced-repetition-bot == 'true' }}
        uses: docker/build-push-action@v3
        with:
          file: spaced-repetition-bot/Dockerfile
          push: true
          tags: ouidockeruser/spaced-repetition-bot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

#      - name: Build and Push Web Image
#        if: ${{ needs.detect-changes.outputs.spaced-repetition-web == 'true' }}
#        uses: docker/build-push-action@v3
#        with:
#          file: spaced-repetition-web/Dockerfile
#          push: true
#          tags: ouidockeruser/spaced-repetition-web:latest
#          cache-from: type=gha
#          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to remote server
    runs-on: ubuntu-latest
    needs: [detect-changes, push-docker-compose-to-remote-server, build-and-push-images-to-dockerhub]
    steps:
      - name: Create .env file
        run: |
          cat << EOF > .env
          TELEGRAM_BOT_DB_USER=${{ secrets.TELEGRAM_BOT_DB_USER }}
          TELEGRAM_BOT_DB_PASSWORD=${{ secrets.TELEGRAM_BOT_DB_PASSWORD }}
          TELEGRAM_BOT_PORT=${{ secrets.TELEGRAM_BOT_PORT }}
          TELEGRAM_BOT_NAME=SpacedRepetitionBot
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_BOT_CREATOR_ID=${{ secrets.TELEGRAM_BOT_CREATOR_ID }}
          GIT_SSH_PASSPHRASE=${{ secrets.GIT_SSH_PASSPHRASE }}
          GIT_WEBHOOK_SECRET=${{ secrets.GIT_WEBHOOK_SECRET }}
          GIT_TOKEN=${{ secrets.GIT_TOKEN }}
          ENCRYPTION_PASSWORD=${{ secrets.ENCRYPTION_PASSWORD }}
          ENCRYPTION_SALT=${{ secrets.ENCRYPTION_SALT }}
          EOF

          # Защищаем файл перед отправкой
          chmod 600 .env

      - name: Copy .env to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: "github-spaced-repetition"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ".env"
          target: "/home/github-spaced-repetition"

      - name: Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: "github-spaced-repetition"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # Немедленный выход при ошибке
            trap 'rm -f .env' EXIT  # Гарантированное удаление .env при выходе
            
            # Обновляем только измененные сервисы
            if [ '${{ needs.detect-changes.outputs.docker-compose }}' = 'true' ]; then
              # При изменении compose перезапускаем весь стек
              echo "Full stack update"
              docker compose down
              docker compose pull --quiet
              docker compose up -d --force-recreate --remove-orphans
            else
              echo "Partial update"
              services_to_update=()
              [ '${{ needs.detect-changes.outputs.spaced-repetition-bot }}' = 'true' ] && services_to_update+=("spaced-repetition-bot")
              [ '${{ needs.detect-changes.outputs.spaced-repetition-web }}' = 'true' ] && services_to_update+=("spaced-repetition-web")
            
              for service in "${services_to_update[@]}"; do
                echo "Updating $service"
                docker compose pull --quiet $service
                docker compose up -d --no-deps --force-recreate --remove-orphans $service
              done
            fi
            
            echo "Current containers:"
            docker ps -a
            
            echo "Cleaning project images..."
            docker image prune -a -f --filter "label=maintainer=ouidockeruser"  # удалить все неиспользуемые образы
            
      - name: Clean local .env
        run: rm -f .env